require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("user.project")
require("user.impatient")
require("user.indentline")
require("user.alpha")
require("user.whichkey")
require("user.autocommands")
--require("user.wilder")
require("user.autosave")
require("user.languagetool")
--require("user.prosesitter")
require("grammar-guard").init()
require("user.bullets")
require("user.notify")
require("user.trouble")
require("user.twilight")
require("user.zen-mode")
require("user.zk-nvim")
--require("user.pywal")
--vim.g.tq_enabled_backends = { "openoffice_en", "mthesaur_txt" }
--vim.g.tq_mthesaur_file = { "~/.config/nvim/thesaurus/mthesaur.txt" }
---vim.g.tq_language = { "en" }
